
DROP DATABASE HOSPITAL;
CREATE DATABASE HOSPITAL;
USE HOSPITAL;
CREATE TABLE PATIENT
(
	PATIENT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	P_FNAME CHAR(20) NOT NULL,
	P_LNAME CHAR(20) ,
	P_GENDER CHAR(1) NOT NULL ,
	DOB DATE
);

CREATE TABLE SPECIALIZATION
(
	SP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SP_NAME CHAR(20)
);

CREATE TABLE WARD
(
	WARD_NUM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NUM_BEDS INT,
	EMPTY_BEDS INT
);

CREATE TABLE EMPLOYEETYPE
(
	EMP_TYPE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
	EMP_TYPE_NAME ENUM('Pharmacist' , 'Doctor' , 'Receptionist')
);

CREATE TABLE MEDICINE
(
	MED_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MED_NAME CHAR(20) NOT NULL,
	MED_PRICE INT NOT NULL,
	MED_DOSE CHAR(10),
	MED_DESC CHAR(30),
	NUM_MEDS INT
);

CREATE TABLE EMPLOYEE
(
	EMP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	EMP_FNAME CHAR(20) NOT NULL,
	EMP_LNAME CHAR(20),
	EMP_JOIN_DATE DATE  NOT NULL,
	EMP_GENDER ENUM('MALE' , 'FEMALE'),
	EMP_SALARY INT,
	EMP_PHONE CHAR(20),
	EMP_TYPE_ID INT NOT NULL,
	EMP_PASSWORD CHAR(50),
	CONSTRAINT FK_EMP_TYPE_ID FOREIGN KEY(EMP_TYPE_ID) REFERENCES EMPLOYEETYPE(EMP_TYPE_ID)
);

CREATE TABLE DOCTOR
(
	EMP_ID INT NOT NULL,
	SP_ID INT NOT NULL,
	DOC_OFFICE INT,
	CONSTRAINT FK_DOC_TYPE_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
	CONSTRAINT FK_DOC_SP_ID FOREIGN KEY (SP_ID) REFERENCES SPECIALIZATION(SP_ID),
	CONSTRAINT PK_DOCTOR PRIMARY KEY (EMP_ID , SP_ID)
);

CREATE TABLE NURSE
(
	EMP_ID INT NOT NULL,
	WARD_NUM INT NOT NULL,
	CONSTRAINT FK_NURSE_EMP_ID FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
	CONSTRAINT FK_NURSE_WARD_NUM FOREIGN KEY(WARD_NUM) REFERENCES WARD(WARD_NUM),
	CONSTRAINT PK_NURSE PRIMARY KEY(EMP_ID , WARD_NUM)
);

CREATE TABLE APPOINTMENT
(
	APP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PATIENT_ID INT NOT NULL,
	EMP_ID INT NOT NULL ,
	MED_ID INT ,
	WARD_NUM INT ,
	APP_DATE DATE ,
	APP_TIME TIME ,
	CONSTRAINT FK_APP_PID FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
	CONSTRAINT FK_APP_EMP_ID FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
	CONSTRAINT FK_APP_MED_ID FOREIGN KEY(MED_ID) REFERENCES MEDICINE(MED_ID),
	CONSTRAINT FK_APP_WARD_NUM FOREIGN KEY (WARD_NUM) REFERENCES WARD(WARD_NUM)
);
CREATE TABLE LOGIN
	(
	LOGIN_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,	
	EMP_ID INT ,
	USERNAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	ROLE ENUM('Pharmacist' , 'Doctor' , 'Receptionist') ,
	-- EMP_TYPE_NAME ENUM('Pharmacist' , 'Doctor' , 'Receptionist') ,
	-- CONSTRAINT FK_LOG_EMP_TYPE_NAME FOREIGN KEY(EMP_TYPE_NAME) REFERENCES EMPLOYEETYPE(EMP_TYPE_NAME) ,
	CONSTRAINT FK_LOG_EMP_ID FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
	
	);

